# name: CI/CD Pipeline

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# env:
#   NODE_ENV: development

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'

#     - name: Install dependencies
#       run: npm install

#     - name: Build
#       run: npm run build

#     - name: Lint
#       run: npm init @eslint/config

#     - name: Test
#       run: npm run test

#   deploy:
#     needs: [build]
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main' && github.event_name == 'push'

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '14.x'

#     - name: Install dependencies
#       run: npm install --production

#     - name: Deploy to Heroku
#       uses: akhileshns/heroku-deploy@v3.12.12
#       with:
#         heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#         heroku_app_name: 'your-heroku-app-name'
#         heroku_email: 'youremail@example.com'
